#!/bin/bash

type=xhtml_no_chunks
tempdir=./build/cll_diffs

rm -rf $tempdir
mkdir -p $tempdir

read_var() {
    VAR=$(grep $1 $2 | xargs)
    IFS="=" read -ra VAR <<< "$VAR"
    echo ${VAR[1]}
}

compare_with=$(read_var COMPARE_WITH .env)
source_dir_old="official/cll_v1.1_"
if [[ compare_with ]]
then
  source_dir_old=official/$compare_with"_"$type
fi

source_dir_new=./build/$type

target_dir_old=$tempdir/diff_old_$type
target_dir_new=$tempdir/diff_new_$type
rm -rf $target_dir_old $target_dir_new

cp -pr $source_dir_old $target_dir_old
cp -pr $source_dir_new $target_dir_new
find $target_dir_old $target_dir_new -name "*.html" -type f | xargs sed -r -i -e 's/<a id="idm[0-9]+"/<a id="idmXXX"/g' -e 's/#idm[0-9]+"/#idmXXX"/g' -e 's/</\n</g'
# Why this needs to be its own line is something I'm not 100%
# clear on, but it just deletes blank lines
find $target_dir_old $target_dir_new -name "*.html" -type f | xargs sed -r -i -e '/^\s*$/d'

echo "Preparing a visual HTML diff file ..."
node $PWD/scripts/diff
prince -vvv --script=scripts/prince_check_margins.js --script=scripts/prince_shave_index.js $tempdir/difference.html -o $tempdir/cll_difference.pdf
prince -vvv --script=scripts/prince_check_margins.js --script=scripts/prince_shave_index.js $tempdir/difference_prefixed.html -o $tempdir/cll_difference_prefixed.pdf
echo "A visual HTML diff is placed in $tempdir/difference.html $tempdir/difference_prefixed.html $tempdir/cll_difference.pdf $tempdir/cll_difference_prefixed.pdf files."

echo
echo
echo "Diffs done.  All files used for diffing can be found in $tempdir if you want to investigate anything yourself."
echo
echo