#!/bin/sh

cat <<EOF
<glossary xmlns='http://docbook.org/ns/docbook'>
<title>Lojban Word Glossary</title>
<para>All definitions in this glossary are brief and unofficial.
Only the published dictionary is a truly official reference for word
definitions.  These definitions are here simply as a quick reference.
</para>

<!-- THIS FILE IS AUTOGENERATED.  DO NOT EDIT OR CHECK IN! -->

EOF

TMPFILE="/tmp/generate_glossary.tmp.$$"

IFS='
'
initial=''
indiv=''

xsltproc --nonet --path . --novalid generate_glossary.xsl cll_preglossary.xml | grep -P '\t' | sort | uniq >$TMPFILE

for line in $(cat $TMPFILE)
do
  slug=$(echo $line | awk -F'\t' '{ print $1 }')
  word=$(echo $line | awk -F'\t' '{ print $2 }' | sed 's/\.//g')
#  echo "$slug--$word"
  newinitial=$(echo $word | cut -c 1)

  if [ "$initial" != "$newinitial" ]
  then
    if [ "$indiv" ]
    then
      echo "</glossdiv>"
    else
      indiv=1
    fi
    echo "<glossdiv><title>$newinitial</title>"
    initial=$newinitial
  fi

  if [ ! -f jbovlaste.xml -o "$(find jbovlaste.xml -mtime +1)" ]
  then
    echo "jbovlaste file is old; refetching." 1>&2
    wget 'http://jbovlaste.lojban.org/export/xml-export.html?lang=en' -O jbovlaste.xml
  fi
  
  rm jbovlaste2.xml
  grep '^<valsi word=' jbovlaste.xml | \
    sed 's/^<valsi word="\([^"]*\)" /###\1### &/' >jbovlaste2.xml

  definition=$(grep -F "###$word### " jbovlaste2.xml | \
      sed -e 's/^[^ ]* //' | \
      sed -e 's/.*<definition>//' -e 's;</definition>.*;;' | \
      sed -e 's/\&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' | \
      sed 's/\s\s*/ /g')

  if [ ! "$(echo $definition | sed 's/\s*//g')" ]
  then
    definition="NO JBOVLASTE DEFINITION FOR \"$word\" FOUND!"
    echo $definition 1>&2
  fi

  cat <<EOF
<glossentry xml:id="valsi-$slug">
<glossterm>$word</glossterm>
<glossdef>
  <para>$definition</para>
</glossdef>
</glossentry>
EOF
done

cat <<EOF

</glossdiv>
</glossary>

EOF

rm $TMPFILE
