#!/bin/sh

cat <<EOF
<glossary xmlns='http://docbook.org/ns/docbook'>
<title>Lojban Word Glossary</title>
<para>All definitions in this glossary are brief and unofficial.
Only the published dictionary is a truly official reference for word
definitions.  These definitions are here simply as a quick reference.
</para>

<!-- THIS FILE IS AUTOGENERATED.  DO NOT EDIT OR CHECK IN! -->

EOF

IFS='
'
initial=''
indiv=''
for line in $(xsltproc --path . --novalid generate_glossary.xsl cll_preglossary.xml | grep -P '\t' | sort | uniq)
do
  slug=$(echo $line | awk -F'\t' '{ print $1 }')
  word=$(echo $line | awk -F'\t' '{ print $2 }')
#  echo "$slug--$word"
  newinitial=$(echo $word | cut -c 1)

  if [ "$initial" != "$newinitial" ]
  then
    if [ "$indiv" ]
    then
      echo "</glossdiv>"
    else
      indiv=1
    fi
    echo "<glossdiv><title>$newinitial</title>"
    initial=$newinitial
  fi

  definition=$(dict --formatted -d 'jbo->en' -h dict.lojban.org $word | \
      sed '/^\s*Notes:\s*/,$d' | grep -A 10 '^\s*Definition:\s*' | \
      tr -d '\012' | sed 's/^\s*Definition:\s*//' | \
      sed 's/\&/\&amp;/g' | sed 's/\s\s*/ /g')

  if [ ! "$(echo $definition | sed 's/\s*//g')" ]
  then
    definition="NO JBOVLASTE DEFINITION FOR \"$word\" FOUND!"
  fi

  cat <<EOF
<glossentry xml:id="jbogloss-$slug">
<glossterm>$word</glossterm>
<glossdef>
  <para>$definition</para>
</glossdef>
</glossentry>
EOF
done

cat <<EOF

</glossdiv>
</glossary>

EOF
