#!/bin/sh

echo '<?xml version="1.0"?>
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V5.0//EN" "dtd/docbook-5.0.dtd" [
  <!ENTITY % iso-pub-ent SYSTEM "iso-pub.ent">
  %iso-pub-ent;
]>

<book xmlns:xlink="http://www.w3.org/1999/xlink">

<!-- THIS FILE IS AUTOGENERATED.  DO NOT EDIT OR CHECK IN! -->

' >cll.xml

testing=""
if [ "$1" = "-t" ]
then
  testing=1
  shift
  echo "Entering testing mode: will replace all external xrefs in each chapter."
fi
#<chapter xml:id="chapter-selbri">
#<section xml:id="section-brivla">

for file in $@
do
  if [ "$testing" ]
  then
    # This breaks working sections/chapters as well as broken ones; oh well.

    chaptertag=$(grep '<chapter ' $file | head -n 1 | sed 's/.*xml:id="//' | sed 's/".*//')
    sectiontag=$(grep '<section ' $file | head -n 1 | sed 's/.*xml:id="//' | sed 's/".*//')

    cat $file | \
      sed "s/<xref linkend=\"chapter-[^\"]*\"/<xref linkend=\"$chaptertag\"/g" | \
      sed "s/<xref linkend=\"cll_chapter[^\"]*\"/<xref linkend=\"$chaptertag\"/g" | \
      sed "s/<xref linkend=\"section-[^\"]*\"/<xref linkend=\"$sectiontag\"/g" >>cll.xml
  else
    cat $file >>cll.xml
  fi
done

cp cll.xml cll_preglossary.xml

echo '</book>' >>cll_preglossary.xml

./generate_glossary.sh >>cll.xml

#rm cll_preglossary.xml

echo '

<index>
<title>General Index</title>
</index>

<index type="lojban-words">
<title>Lojban Words Index</title>
</index>

<index type="lojban-phrases">
<title>Lojban Phrases Index</title>
</index>

<index type="lojban-word-imported">
<title>Lojban Automated Words Index</title>
</index>

<index type="example-imported">
<title>Lojban Examples Index</title>
</index>

</book>' >>cll.xml
