#!/bin/sh

echo '<?xml version="1.0"?>
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V5.0//EN"
               "dtd/docbook-5.0.dtd">

<book xmlns:xlink="http://www.w3.org/1999/xlink">

<!-- THIS FILE IS AUTOGENERATED.  DO NOT EDIT OR CHECK IN! -->

' >cll.xml

if [ "$1" == "-t" ]
then
  echo "Entering testing mode: will replace all external xrefs in each chapter."
fi
<chapter xml:id="selbri">

for file in $@
do
  cat $file >>cll.xml
done

cp cll.xml cll_preglossary.xml

echo '</book>' >>cll_preglossary.xml

generate_glossary.sh >>cll.xml

rm cll_preglossary.xml

echo '

<index type="general">
<title>General Index</title>
</index>

<index type="lojban-words">
<title>Lojban Words Index</title>
</index>

<index type="lojban-phrases">
<title>Lojban Phrases Index</title>
</index>

</book>' >>cll.xml
